version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build latest
          command: docker build -t wahyd4/aria2-ui:1.0.$CIRCLE_BUILD_NUM caddy/.
      - run:
          name: Push
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag luicfer/aria2-ui:1.0.$CIRCLE_BUILD_NUM luicfer/aria2-ui:latest
            docker push luicfer/aria2-ui:1.0.$CIRCLE_BUILD_NUM
            docker push luicfer/aria2-ui:1.0.$CIRCLE_BUILD_NUM
